version: '3'
services:
  db-products-api:
    image: postgres:12
    restart: always
    ports:
      - 43141:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: products-api